apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jenkins_home"
  capacity:
    storage: 4Gi
