apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
#     - name: storage
#       persistentVolumeClaim:
#          claimName: pvc
      - name: docker-sock
        hostPath: 
          path: /var/run/docker.sock
#      serviceAccountName: jenk-kube-adm
      containers:
      - name: jenkins-master-test
        image: jenkinsci/blueocean:1.21.0
        env:
        - name: DOCKER_HUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-hub-secret
              key: username
        - name: DOCKER_HUB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-hub-secret
              key: password
#        image: jenkins/jenkins:lts
#        env:
#        - name: JAVA_OPTS
#          value: -Djenkins.install.runSetupWizard=false
        ports:
        - containerPort: 8080
          name: ui
#        - containerPort: 50000
#          name: agents
#        volumeMounts:
#        - mountPath: /var/jenkins_home
          name: storage
        - mountPath: /var/run/docker.sock
          name: docker-sock